course:
  itemDescription: "Энергия ON: Выходи на новый уровень"
  price: "${ITEM_PRICE}"
telegram:
  api-url: "https://api.telegram.org/"
  webhook-url: "${WEBHOOK_URL}"  # читаем из переменной окружения
  bot-name: "${BOT_NAME}"
  bot-token: "${BOT_TOKEN}"
wayforpay:
  #  merchantAccount: "freelance_user_67b5a584473d6"
  #  secretKey: "03354047d6cedde54829c5ff0035dbe4f29923f6"
  merchantAccount: "${WAYFORPAY_MERCHANT_ACCOUNT}"
  secretKey: "${WAYFORPAY_SECRET_KEY}"
  apiVersion: "1"
  merchantDomainName: "https://www.instagram.com/ira_ravchak"
  currency: "UAH"
  api:
    create_payment: "https://secure.wayforpay.com/pay"
    callback:
      url: "/callback"
server:
  port: "${PORT:5000}"
management:
  endpoints:
    web:
      exposure:
        include: "health"