course:
  itemDescription: "Энергия ON: Выходи на новый уровень"
  price: 1
telegram:
  api-url: "https://api.telegram.org/"
  webhook-url: "https://651d-109-86-217-9.ngrok-free.app"
  bot-name: "learning_course_energy_on_bot"
  bot-token: "7141593917:AAGouMrKk2K7iE6qnCPnb_AOo3H2kq34pZk"
wayforpay:
#  merchantAccount: "freelance_user_67b5a584473d6"
#  secretKey: "03354047d6cedde54829c5ff0035dbe4f29923f6"
  merchantAccount: "test_merch_n1"
  secretKey: "flk3409refn54t54t*FNJRET"
  apiVersion: "1"
  merchantDomainName: "https://www.instagram.com/ira_ravchak"
  currency: "UAH"
  api:
    create_payment: "https://secure.wayforpay.com/pay"
    callback:
      url: "/callback"
spring:
  data:
    redis:
      host: "ec2-34-255-62-139.eu-west-1.compute.amazonaws.com"
      port: 27270
      password: "p34bc23ecfa4ef9b0d7750b16d5c2d0b63edc33c958041fc1d3ab84086ea340b4"
      ssl:
        enabled: true
      database: 0
server:
  port: 5000
management:
  endpoints:
    web:
      exposure:
        include: "health"